### ISSUE TITLE
Specifications

### ISSUE THREAD

**Issue by aamarques** [function3d/petalot#67]
Hy, could you explain about the BOM:

- What's the length of M3 OD 4.2mm Insert Nut for motor mount and electronic box ?
- There's no link for 48mm M6 Rod and I can't found in Ali. The solution is to buy a 50mm and cut ? 
- Is the WeMo Mini D1 must be V4 or V3 works ? 
- 2 wire cable for limit switch, digital signal. What about the AWG size ? 

Thanks

**Comment by function3d** [comment]
- 4.2mm
- 48cm, it is a typo, there is not in aliexpress, you will have to get it in a hardware store, about 48cm the measure is not important since it simply has to be longer than the maximum height of your bottles
- Wemos D1 MINI is powered by 5V, internally it operates at 3.3V and has its own voltage regulator
- Is irrelevant, since it is for a digital signal the cable can be any, preferably thin
